export const CREATE_INDENT_REQUEST = "CREATE_INDENT_REQUEST";
export const CREATE_INDENT_SUCCESS = "CREATE_INDENT_SUCCESS";
export const CREATE_INDENT_FAILURE = "CREATE_INDENT_FAILURE";

export const FETCH_INDENTS_DATA_REQUEST = "FETCH_INDENTS_DATA_REQUEST";
export const FETCH_INDENTS_DATA_SUCCESS = "FETCH_INDENTS_DATA_SUCCESS";
export const FETCH_INDENTS_DATA_FAILURE = "FETCH_INDENTS_DATA_FAILURE";

export const FETCH_INDENT_DATA_REQUEST = "FETCH_INDENT_DATA_REQUEST";
export const FETCH_INDENT_DATA_SUCCESS = "FETCH_INDENT_DATA_SUCCESS";
export const FETCH_INDENT_DATA_FAILURE = "FETCH_INDENT_DATA_FAILURE";

export const EDIT_INDENT_REQUEST = "EDIT_INDENT_REQUEST";
export const EDIT_INDENT_SUCCESS = "EDIT_INDENT_SUCCESS";
export const EDIT_INDENT_FAILURE = "EDIT_INDENT_FAILURE";
