export const FETCH_PROJECTS_NAMES_REQUEST = "FETCH_PROJECTS_NAMES_REQUEST";
export const FETCH_PROJECTS_NAMES_SUCCESS = "FETCH_PROJECTS_NAMES_SUCCESS";
export const FETCH_PROJECTS_NAMES_FAILURE = "FETCH_PROJECTS_NAMES_FAILURE";

export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE";

export const EDIT_PROJECT_REQUEST = "EDIT_PROJECT_REQUEST";
export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS";
export const EDIT_PROJECT_FAILURE = "EDIT_PROJECT_FAILURE";

export const FETCH_PROJECT_COUNT_REQUEST = "FETCH_PROJECT_COUNT_REQUEST";
export const FETCH_PROJECT_COUNT_SUCCESS = "FETCH_PROJECT_COUNT_SUCCESS";
export const FETCH_PROJECT_COUNT_FAILURE = "FETCH_PROJECT_COUNT_FAILURE";

export const FETCH_PROJECTS_DATA_REQUEST = "FETCH_PROJECTS_DATA_REQUEST";
export const FETCH_PROJECTS_DATA_SUCCESS = "FETCH_PROJECTS_DATA_SUCCESS";
export const FETCH_PROJECTS_DATA_FAILURE = "FETCH_PROJECTS_DATA_FAILURE";

export const FETCH_PROJECT_DATA_REQUEST = "FETCH_PROJECT_DATA_REQUEST";
export const FETCH_PROJECT_DATA_SUCCESS = "FETCH_PROJECT_DATA_SUCCESS";
export const FETCH_PROJECT_DATA_FAILURE = "FETCH_PROJECT_DATA_FAILURE";

export const EDIT_PROJECT_DATA_REQUEST = "EDIT_PROJECT_DATA_REQUEST";
export const EDIT_PROJECT_DATA_SUCCESS = "EDIT_PROJECT_DATA_SUCCESS";
export const EDIT_PROJECT_DATA_FAILURE = "EDIT_PROJECT_DATA_FAILURE";

export const DELETE_PROJECT_DATA_REQUEST = "DELETE_PROJECT_DATA_REQUEST";
export const DELETE_PROJECT_DATA_SUCCESS = "DELETE_PROJECT_DATA_SUCCESS";
export const DELETE_PROJECT_DATA_FAILURE = "DELETE_PROJECT_DATA_FAILURE";