export const FETCH_USER_NAMES_REQUEST = "FETCH_USER_NAMES_REQUEST";
export const FETCH_USER_NAMES_SUCCESS = "FETCH_USER_NAMES_SUCCESS";
export const FETCH_USER_NAMES_FAILURE = "FETCH_USER_NAMES_FAILURE";

export const CREATE_MEMBER_REQUEST = "CREATE_MEMBER_REQUEST";
export const CREATE_MEMBER_SUCCESS = "CREATE_MEMBER_SUCCESS";
export const CREATE_MEMBER_FAILURE = "CREATE_MEMBER_FAILURE";

export const FETCH_USER_COUNT_REQUEST = "FETCH_USER_COUNT_REQUEST";
export const FETCH_USER_COUNT_SUCCESS = "FETCH_USER_COUNT_SUCCESS";
export const FETCH_USER_COUNT_FAILURE = "FETCH_USER_COUNT_FAILURE";

export const FETCH_USERS_DATA_REQUEST = "FETCH_USERS_DATA_REQUEST";
export const FETCH_USERS_DATA_SUCCESS = "FETCH_USERS_DATA_SUCCESS";
export const FETCH_USERS_DATA_FAILURE = "FETCH_USERS_DATA_FAILURE";

export const FETCH_USER_DATA_REQUEST = "FETCH_USER_DATA_REQUEST";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAILURE = "FETCH_USER_DATA_FAILURE";

export const EDIT_USER_DATA_REQUEST = "EDIT_USER_DATA_REQUEST";
export const EDIT_USER_DATA_SUCCESS = "EDIT_USER_DATA_SUCCESS";
export const EDIT_USER_DATA_FAILURE = "EDIT_USER_DATA_FAILURE";

export const DELETE_USER_DATA_REQUEST = "DELETE_USER_DATA_REQUEST";
export const DELETE_USER_DATA_SUCCESS = "DELETE_USER_DATA_SUCCESS";
export const DELETE_USER_DATA_FAILURE = "DELETE_USER_DATA_FAILURE";