export const FETCH_USER_NAMES_REQUEST = "FETCH_USER_NAMES_REQUEST";
export const FETCH_USER_NAMES_SUCCESS = "FETCH_USER_NAMES_SUCCESS";
export const FETCH_USER_NAMES_FAILURE = "FETCH_USER_NAMES_FAILURE";

export const CREATE_MEMBER_REQUEST = "CREATE_MEMBER_REQUEST";
export const CREATE_MEMBER_SUCCESS = "CREATE_MEMBER_SUCCESS";
export const CREATE_MEMBER_FAILURE = "CREATE_MEMBER_FAILURE";

export const FETCH_USER_COUNT_REQUEST = "FETCH_USER_COUNT_REQUEST";
export const FETCH_USER_COUNT_SUCCESS = "FETCH_USER_COUNT_SUCCESS";
export const FETCH_USER_COUNT_FAILURE = "FETCH_USER_COUNT_FAILURE";

export const FETCH_USERS_DATA_REQUEST = "FETCH_USERS_DATA_REQUEST";
export const FETCH_USERS_DATA_SUCCESS = "FETCH_USERS_DATA_SUCCESS";
export const FETCH_USERS_DATA_FAILURE = "FETCH_USERS_DATA_FAILURE";

export const FETCH_USER_DATA_REQUEST = "FETCH_USER_DATA_REQUEST";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAILURE = "FETCH_USER_DATA_FAILURE";

export const EDIT_USER_DATA_REQUEST = "EDIT_USER_DATA_REQUEST";
export const EDIT_USER_DATA_SUCCESS = "EDIT_USER_DATA_SUCCESS";
export const EDIT_USER_DATA_FAILURE = "EDIT_USER_DATA_FAILURE";

export const DELETE_USER_DATA_REQUEST = "DELETE_USER_DATA_REQUEST";
export const DELETE_USER_DATA_SUCCESS = "DELETE_USER_DATA_SUCCESS";
export const DELETE_USER_DATA_FAILURE = "DELETE_USER_DATA_FAILURE";

export const FETCH_PROJECTS_NAMES_REQUEST = "FETCH_PROJECTS_NAMES_REQUEST";
export const FETCH_PROJECTS_NAMES_SUCCESS = "FETCH_PROJECTS_NAMES_SUCCESS";
export const FETCH_PROJECTS_NAMES_FAILURE = "FETCH_PROJECTS_NAMES_FAILURE";

export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE";

export const EDIT_PROJECT_REQUEST = "EDIT_PROJECT_REQUEST";
export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS";
export const EDIT_PROJECT_FAILURE = "EDIT_PROJECT_FAILURE";

export const FETCH_PROJECT_COUNT_REQUEST = "FETCH_PROJECT_COUNT_REQUEST";
export const FETCH_PROJECT_COUNT_SUCCESS = "FETCH_PROJECT_COUNT_SUCCESS";
export const FETCH_PROJECT_COUNT_FAILURE = "FETCH_PROJECT_COUNT_FAILURE";

export const FETCH_PROJECTS_DATA_REQUEST = "FETCH_PROJECTS_DATA_REQUEST";
export const FETCH_PROJECTS_DATA_SUCCESS = "FETCH_PROJECTS_DATA_SUCCESS";
export const FETCH_PROJECTS_DATA_FAILURE = "FETCH_PROJECTS_DATA_FAILURE";

export const FETCH_PROJECT_DATA_REQUEST = "FETCH_PROJECT_DATA_REQUEST";
export const FETCH_PROJECT_DATA_SUCCESS = "FETCH_PROJECT_DATA_SUCCESS";
export const FETCH_PROJECT_DATA_FAILURE = "FETCH_PROJECT_DATA_FAILURE";

export const EDIT_PROJECT_DATA_REQUEST = "EDIT_PROJECT_DATA_REQUEST";
export const EDIT_PROJECT_DATA_SUCCESS = "EDIT_PROJECT_DATA_SUCCESS";
export const EDIT_PROJECT_DATA_FAILURE = "EDIT_PROJECT_DATA_FAILURE";

export const DELETE_PROJECT_DATA_REQUEST = "DELETE_PROJECT_DATA_REQUEST";
export const DELETE_PROJECT_DATA_SUCCESS = "DELETE_PROJECT_DATA_SUCCESS";
export const DELETE_PROJECT_DATA_FAILURE = "DELETE_PROJECT_DATA_FAILURE";

export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";

export const FETCH_TASKS_DATA_REQUEST = "FETCH_TASKS_DATA_REQUEST";
export const FETCH_TASKS_DATA_SUCCESS = "FETCH_TASKS_DATA_SUCCESS";
export const FETCH_TASKS_DATA_FAILURE = "FETCH_TASKS_DATA_FAILURE";

export const CREATE_INDENT_REQUEST = "CREATE_INDENT_REQUEST";
export const CREATE_INDENT_SUCCESS = "CREATE_INDENT_SUCCESS";
export const CREATE_INDENT_FAILURE = "CREATE_INDENT_FAILURE";

export const FETCH_INDENTS_DATA_REQUEST = "FETCH_INDENTS_DATA_REQUEST";
export const FETCH_INDENTS_DATA_SUCCESS = "FETCH_INDENTS_DATA_SUCCESS";
export const FETCH_INDENTS_DATA_FAILURE = "FETCH_INDENTS_DATA_FAILURE";

export const CREATE_VENDOR_REQUEST = "CREATE_VENDOR_REQUEST";
export const CREATE_VENDOR_SUCCESS = "CREATE_VENDOR_SUCCESS";
export const CREATE_VENDOR_FAILURE = "CREATE_VENDOR_FAILURE";

export const FETCH_VENDORS_DATA_REQUEST = "FETCH_VENDORS_DATA_REQUEST";
export const FETCH_VENDORS_DATA_SUCCESS = "FETCH_VENDORS_DATA_SUCCESS";
export const FETCH_VENDORS_DATA_FAILURE = "FETCH_VENDORS_DATA_FAILURE";

export const CREATE_PURCHASE_REQUEST = "CREATE_PURCHASE_REQUEST";
export const CREATE_PURCHASE_SUCCESS = "CREATE_PURCHASE_SUCCESS";
export const CREATE_PURCHASE_FAILURE = "CREATE_PURCHASE_FAILURE";

export const FETCH_INDENT_DATA_REQUEST = "CREATE_INDENT_DATA_REQUEST";
export const FETCH_INDENT_DATA_SUCCESS = "CREATE_INDENT_DATA_SUCCESS";
export const FETCH_INDENT_DATA_FAILURE = "CREATE_INDENT_DATA_FAILURE";

export const CREATE_ISSUE_REQUEST = "CREATE_ISSUE_DATA_REQUEST";
export const CREATE_ISSUE_SUCCESS = "CREATE_ISSUE_SUCCESS";
export const CREATE_ISSUE_FAILURE = "CREATE_ISSUE_FAILURE";
