export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";

export const FETCH_TASKS_DATA_REQUEST = "FETCH_TASKS_DATA_REQUEST";
export const FETCH_TASKS_DATA_SUCCESS = "FETCH_TASKS_DATA_SUCCESS";
export const FETCH_TASKS_DATA_FAILURE = "FETCH_TASKS_DATA_FAILURE";

export const FETCH_PROJECT_TASKS_DATA_REQUEST =
  "FETCH_PROJECT_TASKS_DATA_REQUEST";
export const FETCH_PROJECT_TASKS_DATA_SUCCESS =
  "FETCH_PROJECT_TASKS_DATA_SUCCESS";
export const FETCH_PROJECT_TASKS_DATA_FAILURE =
  "FETCH_PROJECT_TASKS_DATA_FAILURE";

export const FETCH_PROJECT_TASK_DATA_REQUEST =
  "FETCH_PROJECT_TASK_DATA_REQUEST";
export const FETCH_PROJECT_TASK_DATA_SUCCESS =
  "FETCH_PROJECT_TASK_DATA_SUCCESS";
export const FETCH_PROJECT_TASK_DATA_FAILURE =
  "FETCH_PROJECT_TASK_DATA_FAILURE";

export const EDIT_PROJECT_TASK_DATA_REQUEST = "EDIT_PROJECT_TASK_DATA_REQUEST";
export const EDIT_PROJECT_TASK_DATA_SUCCESS = "EDIT_PROJECT_TASK_DATA_SUCCESS";
export const EDIT_PROJECT_TASK_DATA_FAILURE = "EDIT_PROJECT_TASK_DATA_FAILURE";

export const DELETE_PROJECT_TASK_DATA_REQUEST =
  "DELETE_PROJECT_TASK_DATA_REQUEST";
export const DELETE_PROJECT_TASK_DATA_SUCCESS =
  "DELETE_PROJECT_TASK_DATA_SUCCESS";
export const DELETE_PROJECT_TASK_DATA_FAILURE =
  "DELETE_PROJECT_TASK_DATA_FAILURE";
